kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podlister
subjects:
  - kind: ServiceAccount
    name: podlister
    namespace: kafka-dev
roleRef:
  kind: ClusterRole
  name: podlister
  apiGroup: rbac.authorization.k8s.io